# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish React-Dim-Actions

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: CultureHQ/actions-yarn@v1.0.1
        with:
          node-version: 16
      - run: yarn install
      - run: yarn test
      - run: yarn build

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: CultureHQ/actions-yarn@v1.0.1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: echo ${{secrets.publish.PUBLISH_TOKEN}}
      - run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.publish.PUBLISH_TOKEN}}
